[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.83.0"

[workspace.dependencies]
thiserror = "2"
winnow = "0.6.24"
strum = "0.26.3"
beef = "0.5.2"
rstest = "0.23.0"
nutype = "0.5.1"
vec1 = "1.12.1"
